image:
  repository: 369367720723.dkr.ecr.eu-central-1.amazonaws.com/aiops-quality-api
  tag: v20260301125441
  pullPolicy: IfNotPresent

service:
  port: 8000

env:
  APP_NAME: aiops-quality-api
  DRIFT_THRESHOLD: "0.9"
  MODEL_PATH: /models/model.pkl

resources: {}
