apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - aiops-quality
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
